### ISSUE TITLE
[Strory] Correct methods for authorization using aws default profile

### ISSUE THREAD

**Issue by AutoClouds** [AutoClouds/awsCloud#5]
I want to chose one decision from two:
1. Use profile interface
2. Use Client interface

![image](https://user-images.githubusercontent.com/80399750/111671383-f3305600-8829-11eb-9584-dd9823912223.png)

**Comment by Gidroid** [comment]
Done in 447bccc04cdfb2fb5df5bc125aa90caa98f31933 commit
